[package]
name = "rustsearch"
version = "0.1.0"
authors = ["Takuya Asano <takuya.a@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.2.1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
