[package]
name = "rustsearch"
version = "0.1.0"
authors = ["Takuya Asano <takuya.a@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
